version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    image: php:8.2-fpm
    container_name: php
    volumes:
      - ./app:/var/www/html
